services:

  backend:
    image: binkybarnes/harmony-backend
    environment:
      ROCKET_PORT: "5500"
      ROCKET_ADDRESS: "0.0.0.0"
      RUST_ENV: "production"
      ROCKET_DATABASES: "{harmony_db={url=\"postgresql://postgres:${POSTGRES_PASSWORD}@db:5432\"}}"
      JWT_SECRET: "${JWT_SECRET}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_REGION: "${AWS_REGION}"
      S3_IMAGE_BUCKET: "${S3_IMAGE_BUCKET}"
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5500:5500"
    depends_on:
      - db
  db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./backend/init-db:/docker-entrypoint-initdb.d

  frontend:
    image: binkybarnes/harmony-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - ./ssl:/etc/ssl/certs

volumes:
  db:
    driver: local
